FROM python:3.6
ENV VALOHAI_CONFIG_DIR /work/.valohai
RUN pip install tensorflow==1.2.0
RUN pip install opencv-python
RUN pip install tqdm
RUN pip install tflearn
RUN pip install argparse
RUN pip install h5py
RUN pip install valohai-cli
